### ISSUE TITLE
Mobile - Implement 3D model file upload / download

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#367] opened 2024-11-25 12:15 UTC
### Issue Description

In the mobile app, implementation for uploading and downloading 3D model files (with .obj extension) through the backend service will be implemented. Users will be able to upload files during post creation, and download files seamlessly while browsing.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment] 2024-11-25 13:19
The feature has been implemented. Related issue: #368

**Comment by onurcerli** [comment] 2024-11-29 12:03
The upload feature works as intended. However, the download feature is not implemented yet and for customer milestone 2, we do not plan to implement it. So, closing the issue.

**Closed as completed by onurcerli** 2024-11-29 12:03 UTC
Labels: Type: Enhancement, Priority: High, Duration: Mid, Status: Completed
