### ISSUE TITLE
Mobile - Implement follow category feature

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#354] opened 2024-11-24 13:42 UTC
### Issue Description

In the mobile app, the follow category feature will be implemented. Users will be able to follow categories that they are interested in.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by edonmez01** [comment] 2024-11-24 14:58
The feature has been implemented. Relevant pull request: #356

**Comment by onurcerli** [comment] 2024-11-29 11:55
The feature works as intended. Closing the issue.

**Closed by onurcerli** 2024-11-29 11:55 UTC
Labels: Type: Enhancement, Priority: High, Status: Review Needed, Duration: Mid
