### ISSUE TITLE
Mobile - Connect profile page to backend

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#372] opened 2024-11-25 16:20 UTC
### Issue Description

The profile page in the mobile app will be connected to backend. The page will include the latest posts of the user.

### Issue Due Date

25/11/2024 22:00

### Reviewer

@onurcerli

### Revision Due Date

25/11/2024 22:00

**Comment by onurcerli** [comment] 2024-11-29 12:06
It works as intended. The users can view their posts from their profile screen. Closing the issue.

**Closed as completed by onurcerli** 2024-11-29 12:06 UTC
Labels: Type: Enhancement, Priority: High, Duration: Mid, Status: Completed
