### ISSUE TITLE
Mobile - Enhancing leaderboard screen

### ISSUE THREAD

**Issue by AliAlperenSonmez** [bounswe/bounswe2024group8#460] opened 2024-12-20 12:49 UTC
### Issue Description

Leaderboard screen should be enhanced with links to profiles and posts. User profile photos should be added as well.

### Issue Due Date

15/12/2024

### Reviewer

@onurcerli

### Revision Due Date

15/12/2024

**Comment by AliAlperenSonmez** [comment] 2024-12-20 12:49
Leaderboard screen is enhanced and completed.

**Comment by onurcerli** [comment] 2024-12-20 13:31
Implementation is solid and works as intended. Closing the issue...

**Closed by onurcerli** 2024-12-20 13:31 UTC
Labels: Type: Enhancement, Priority: Medium, Duration: Mid, Status: Completed
