### ISSUE TITLE
Backend - Fix getPostResponseById endpoint reaction status

### ISSUE THREAD

**Issue by oguzkagnici** [bounswe/bounswe2024group8#362] opened 2024-11-24 20:38 UTC
### Issue Description

I will fix a problem that causes post responses to return with the post owner reaction information.

### Issue Due Date

26/11/2024

### Reviewer

@erselcanakcili

### Revision Due Date

26/11/2024

**Comment by erselcanakcili** [comment] 2024-11-25 04:06
Bug is fixed now and everything works as intended.

**Closed by erselcanakcili** 2024-11-25 04:06 UTC
Labels: Type: Bug
