### ISSUE TITLE
Mobile - Implement profile screen

### ISSUE THREAD

**Issue by edonmez01** [bounswe/bounswe2024group8#319] opened 2024-11-19 13:01 UTC
### Issue Description

In the mobile app, the profile screen will be implemented in accordance with requirement 1.1.6. The profile page will include the following info about the user:
- Profile picture
- Tournament points
- List of followers / followed users
- Latest posts and comments

### Issue Due Date

24/11/2024 00:00

### Reviewer

@onurcerli

### Revision Due Date

24/11/2024 00:00

**Comment by edonmez01** [comment] 2024-11-29 10:15
The profile screen has been enhanced with the necessary features, and has been connected to the backend.

**Comment by onurcerli** [comment] 2024-11-29 11:54
The screen design is good and the interactive parts of the screen works as intended. Closing the issue.

**Closed by onurcerli** 2024-11-29 11:54 UTC
Labels: Type: Enhancement, Priority: High, Status: Review Needed, Duration: Long
